server:
  host: "0.0.0.0"
  port: 9191
  logger:
    level: 5  # 0-Panic, 1-Fatal, 2-Error, 3-Warn, 4-Info, 5-Debug, 6-Trace
redis:
  host: "127.0.0.1"
  port: 6379
  username: ""
  password: ""
  # 选择数据库
  database: 7
  # 连接时是否重置
  reset: true
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "86132292"
  dbname: "cercis"
  sslmode: "disable"
  timezone: "Asia/Shanghai"
# SMS 短信服务，目前使用阿里云
sms:
  region: "cn-beijing"
  accesskey: "<aliyun-sms-accesskey>"
  secret: "<aliyun-sms-secret>"
  signname: "幻想乡"
  templatecode: "<sms-template-code>"
